version: "3.4"
services:
  pyth2:
    network_mode: host
    container_name: pyth2
    build:
      context: .
    environment:
      - KAGGLE_USERNAME=$KAGGLE_USERNAME
      - KAGGLE_KEY=$KAGGLE_KEY
    volumes:
      - ./:/app/:rw
